README.md
Replace the use of whitelist with allowlist
=> docs: use more inclusive language

list_uBlacklist.txt, list_uBlacklist_nuclear.txt
- Fixed a few typos and removed some duplicate entries
- Moved around some entries to the category they belong to
- Moved the "Going nuclear" category from the normal list to the nuclear list where it belongs, no need to have those in both lists
=> Organization

list.txt, list_uBlacklist.txt, noai_hosts.txt
Added mythmaker.ai; uses AI to procedurally generate text-based game content, but couldn't confirm whether the artwork is also AI generated or not.
=> Added mythmaker.ai

list.txt, list_uBlacklist.txt
discovered this site accidentally when testing if the filter worked haha
might also be a good place to find other sites to block since it is a list of a bunch of ai "tools"
=> Add aitree.io

list.txt, list_uBlacklist.txt
I've wasted 20 minutes to follow their instructions on docker which were hallicinated from AI. Also I checked the impressum and their posts and it's just another content farm
=> Add trycatchdebug.net

list.txt, list_uBlacklist.txt
=> Add codeease

list.txt, list_uBlacklist.txt, noai_hosts.txt
Completely AI generated blog about mushrooms
=> Add amhuru.com

list.txt, list_uBlacklist.txt
these stock sites use ai images so i added em
never opened a pull request (on purpose) before so hopefully im doing this right!!
=> AI Stock Images

list.txt, list_uBlacklist.txt, noai_hosts.txt
=> Add impossibleimages.ai

list.txt, list_uBlacklist.txt, noai_hosts.txt
=> Add https://inspiringdesigns.net/

list.txt, list_uBlacklist.txt
The "athena" part of the website contains ai generated responses for coding questions, they appear in search results
=> Add shecodes.io/athena

list.txt, list_uBlacklist.txt, noai_hosts.txt
Site hosting AI images and AI aggregate reviews of games
=> Blocking gamer.se

list.txt, list_uBlacklist.txt, noai_hosts.txt
=> Add viggle.ai

list.txt, list_uBlacklist.txt, noai_hosts.txt
This PR also addresses [issue #91](https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/issues/91)
=> Add ciciai.com, aistickr.com

list.txt, list_uBlacklist.txt, noai_hosts.txt
This website contains only AI generated content and confidently written factually wrong content. Most of the website exists to promote youtube videos about AI
=> Add madpenguin.org

list.txt, list_uBlacklist.txt, noai_hosts.txt
=> added julius.ai, chatbot.com, getmerlin.in

list.txt, list_uBlacklist.txt
Adding [queenskisivuli](https://medium.com/@queenskisivuli), another AI Medium account. Basically:
- **August 9, 2022:** [First post](https://medium.com/@queenskisivuli/software-engineering-practices-14dbc4e7f96b) starting with programming, with stock image that still has the watermark
- **April 7, 2023:** [Third post](https://medium.com/@queenskisivuli/how-blockchain-technology-can-enhance-certificate-verification-256908405c0d) started including AI images, also started posting about blockchains around this period, but mostly JavaScript
- **November 16, 2023:** [Started posting about AI](https://medium.com/@queenskisivuli/unleashing-the-power-of-agent-swarms-the-future-of-autonomous-ai-c1fe476bd45b)
=> Add Medium: queenskisivuli

list_uBlacklist.txt
uBlacklist accused the changed lines of contain syntax errors. Changed them to use proper comment syntax.
=> Fix Redbubble section comments in `list_uBlacklist.txt`

list.txt
Some GitHub Web UI elements that contain GitHub Copilot
=> Add GitHub Copilot

noai_hosts.txt
Adding a French specialized AI : chat.mistral.ai
=> Adding a French specialized AI

list_uBlacklist.txt
The channel puts out an endless stream of AI-generated slop "tutorials".
=> Add @TheDebugZone to YouTube blocklist

list.txt, list_uBlacklist.txt, noai_hosts.txt
Hello! I'm not sure whether it's better to make an issue for each website or a PR containing a few additions together. Hope this is all good :D
=> forkful.ai, Ancient Pyramid Tales (YouTube) & heatware.net

noai_hosts.txt
This site states that they are using AI to "generate explanations for songs".
Thank you :)
=> Add songtell to AI list

list.txt
Almost entirely AI generated site, from the images to the articles. They plague the top searches for any Duolingo related questions.
=> Add 'duolingoguides.com'

list.txt, list_uBlacklist.txt, noai_hosts.txt
Most if not every article is 100% AI Generated (ex : [This article](https://spca.education/windows-powershell-scripts-with-gui/) contains "Creating a full-fledged Windows PowerShell script with a graphical user interface (GUI) for system administration is a complex task and beyond the scope of a single response.", and also most thumbnails are also AI with their logo on it.
=> Add SP Cloud Academy (spca.education)

list.txt, list_uBlacklist.txt
=> add deepwiki.com
